### ISSUE TITLE
This is stupid

### ISSUE THREAD

**Issue by AshesOfEther** [shiftos-game/ShiftOS#1]
We have already fought the ShiftOS war,  but our opponents overwhelmed us, and despite our best efforts, we lost in the end. Now, that war is over, and people have moved on. Anyone who tries to continue to fight won't get what they want, and ultimately waste their own time.

Just to be clear, I'm not one of those "ShiftOS sux it needs 2 die", Infact, it's already dead. For your own sake, you should just put your "I should revive ShiftOS" thought down for now

**Comment by ghost** [comment]
Woof.

**Comment by ghost** [comment]
Totally not working on an actually good game similar to shiftos with the same people that made shiftos 1.0

**Comment by ghost** [comment]
And totally not spamming this repo.

**Comment by AshesOfEther** [comment]
An actually good game similar to ShiftOS? In the case of working on it with some of the ShiftOS 1.0 guys, you might have some luck. Just don't yell at them if it fails

**Comment by TheDarkBomber** [comment]
The game has been signed dead by Micheal VanOverbeek by closing all services. This includes:
* Deleting all ShiftOS Micheal VanOverbeek videos.
* Deleting the repository and organization.
* Blocking off access to the forums.
* Deleting Sysop Adventures, which is only remotely related to ShiftOS.

He is not going to bring the game back the way it is. This new project will create a better version. Stay tuned - NewSHIFT.

**Comment by AshesOfEther** [comment]
Nobody will play your game. If you look at how many people we lost each time a rewrite of ShiftOS was made and the fact that this won't have the resources that the real game had, you'll get the undeniable result of what I started out saying

**Comment by ghost** [comment]
I suggest you read farther into it, mr. bomber.

Project: Plex is what people are truly waiting for. I have evidence. I'm
also actually accepting user feedback. ShiftOS won't be dead for long.

Alkaline out.​

P.S. apparently "darkie" was a racial slur... did NOT intend it in that way, didn't even realize it at the time. It was just a play on thedarkbomber's username. Apologies if I offended anyone.

**Comment by ghost** [comment]
Also, judging by the fact there LITERALLY hasn't been any code in the repo in like... a week... proves we're far ahead of you.

Alkaline truly out.

**Comment by AshesOfEther** [comment]
"Project: Plex is what people are truly waiting for." -WatercolorGames

LOL

**Comment by ghost** [comment]
No, I'm serious. I'm collecting feedback from past ShiftOS players about
what they'd want to see in a game like it if said game were to be made.

Plex is that game.

**Comment by AshesOfEther** [comment]
I have discovered that

**Comment by TheDarkBomber** [comment]
ShiftOS NewSHIFT will become more refined. We'll make it better, one way or another.

**Comment by AshesOfEther** [comment]
Alright. But let's first write some actual code, shall we?

**Comment by TheDarkBomber** [comment]
There's a new logo.

**Comment by AshesOfEther** [comment]
👏👏
