### ISSUE TITLE
Login function is totally broken

### ISSUE THREAD

**Issue by AShifter** [shiftos-game/ShiftOS#101]
When you try to login to the MUD at the start of the game, you will be redirected to the register page. Then, when you fill that out, it will give you a Shiftorium error. I'll send a crash report once I have time.

**Comment by ComputeLinux** [comment]
are you using the appveyor build

**Comment by AShifter** [comment]
I'm using Beta 1.2

**Comment by AShifter** [comment]
I'll get back to you with a crash report tomorrow.

**Comment by ComputeLinux** [comment]
or you could just use the appveyor build

**Comment by AShifter** [comment]
lol
