### ISSUE TITLE
Game does not save on exit

### ISSUE THREAD

**Issue by AShifter** [shiftos-game/ShiftOS#107]
This is pretty urgent. The game does not save (at least my codepoints) after hitting Shutdown. Opening a terminal before shutdown makes the terminal read out `Saving game to disk...   ...Done` before exiting the application. I resolved the issue by typing `sos.save` before shutting down.

This happened in both Visual Studio 2017, and after downloading the AppVeyor build (standalone).

**Comment by wowmom98** [comment]
This is already an issue.

**Comment by AShifter** [comment]
(a very old issue)
