### ISSUE TITLE
Port litterally everything to OpenGL/Gwen

### ISSUE THREAD

**Issue by ComputeLinux** [shiftos-game/ShiftOS#112]
# Important
- [x] System Renderer
- [x] Desktop
  - [x] Panel
    - [ ] Panel Notifications
    - [ ] Panel Taskbar
    - [x] App Launcher
- [ ] Window Manager
  - [ ] Terminal
  - [ ] Notifications
  - [ ] Shifter
  - [ ] Shiftorium
  - [ ] OOBE
  - [ ] Tutorial Box

# Less Important
- [ ] About
- [ ] Artpad
- [ ] Audio Player
- [ ] Calculator
- [ ] Chat
- [ ] Color Picker
- [ ] Downloader
- [ ] File Dialog
- [ ] File Skimmer
- [ ] Format Editor
- [ ] Graphic Picker
- [ ] MUD Control Center
- [ ] Name Changer
- [ ] Pong
- [ ] Screensavers
- [ ] ShiftLotto
- [ ] Shiftletters
- [ ] Shiftnet
- [ ] Shiftsweeper
- [ ] Shop Item Creator
- [ ] Textpad

**Comment by AShifter** [comment]
Where's ShiftLotto? r we nut convertin dat too?

**Comment by Daniel11420** [comment]
noice idea

# **_do it_**

**Comment by MichaelTheShifter** [comment]
Please either provide constructive discussion about the issue or do not
comment. Thanks.
