### ISSUE TITLE
Tutorial error.

### ISSUE THREAD

**Issue by Daniel11420** [shiftos-game/ShiftOS#113]
Hello! I recently tried playing ShiftOS. I completed the tutorial. The game closed after completion. If I re-launch the game, it takes me back to the tutorial. I asked @pfgithub for help using discord, and he couldn't find a solution either. If I try closing the window the tutorial is in, game crashes with pop-up saying that an error occured and the game had to shut down.

If someone is gonna contact me about this, please contact me on discord. I accept all friend requests. @Daniel11420 / kiziolek06#0167

It said it made a crash.txt. Here is what it says (when I close the window in which the tutorial is, like @pfgithub told me to):

>  === ShiftOS.WinForms has crashed. === 
> 
> Game:           ShiftOS.WinForms
> Description:    I wanted to put a bunch of swears in this description but Rylan hated the idea and when I committed it, William reverted it. Now it's in the latest AppVeyor build until I commit this. Then, THIS will be in appveyor...
> 
> Basic Information For User:
> ---------------------------------
> 
> When:   20.03.2017 17:22:41
> Why:    No se puede obtener acceso al objeto desechado. (a note from Daniel; this is in spanish)
> Nombre del objeto: 'Oobe'. (spanish, again.) (name of object:)
> What:   ObjectDisposedException
> 
> We, at the ShiftOS Development Team, apologise for your game crash,
> we will take this bug report seriously - and it has been emailed
> to the development team of ShiftOS, thank you for enjoying our game!
> 
> Advanced Information (for experts and developers):
> ----------------------------------------------------
> 
> Host system information:
> ---------------------------------
> 
> Operating system:   Win32NT
> Version:            Microsoft Windows NT 6.2.9200.0
> Is 64-bit:          True
> ShiftOS exec path:  C:\Users\kizio_000\Desktop\ShiftOS 1.0 Beta 1.4\ShiftOS.WinForms.exe
> 
> Advanced Host Information:
> ---------------------------------
> 
> CPU Name:           AMD E1-2500 APU with Radeon(TM) HD Graphics    
> Physical RAM Installed:         4294967296 B
> GPU Name:           AMD Radeon HD 8200 / R3 Series
> 
> ShiftOS basic information:
> ---------------------------------
> 
> ShiftOS Version:    1.0.6279.18833
> ShiftOS Date:       11.03.2017 10:27:48
> 
> ShiftOS environment information:
> ---------------------------------
> 
> Is Save loaded:             True
> Paths loaded in system:     ["classic = C:\\ShiftOS","root = 0:","system = 0:/system","home = 0:/home","documents = 0:/home/documents","desktop = 0:/home/desktop","pictures = 0:/home/pictures","local = 0:/system/local","english.local = 0:/system/local/english.local","deutsch.local = 0:/system/local/deutsch.local","verbose.local = 0:/system/local/verbose.local","data = 0:/system/data","applauncher = 0:/system/applauncher","save.json = 0:/system/data/save.json","user.dat = 0:/system/data/user.dat","notifications.dat = 0:/system/data/notifications.dat","skin = 0:/system/data/skin","programs = 0:/system/programs","kernel.sft = 0:/system/kernel.sft","conf.sft = 0:/system/conf.sft","current = 0:/system/data/skin/current","skin.json = 0:/system/data/skin/current/skin.json","images = 0:/system/data/skin/current/images"]
> 
> 
> Crash: ObjectDisposedException
> --------------------------------------------
> 
> Exception message:              No se puede obtener acceso al objeto desechado.
> Nombre del objeto: 'TerminalBox'.
> HResult (this is technical):    -2146232798
> Has inner exception:            False
> Stack trace:
>    en System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
>    en System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
>    en System.Windows.Forms.Control.Invoke(Delegate method)
>    en ShiftOS.WinForms.WinformsDesktop.InvokeOnWorkerThread(Action act)
>    en ShiftOS.Engine.Desktop.InvokeOnWorkerThread(Action act)
>    en ShiftOS.Engine.TerminalTextWriter.Write(String value)
>    en System.IO.TextWriter.SyncTextWriter.Write(String value)
>    en System.Console.Write(String value)
>    en ShiftOS.Engine.ServerManager.<>c.<Initiate>b__31_0(Object o, NetReceivedEventArgs`1 a)
>    en NetSockets.NetBaseClient`1.stream_OnReceived(Object sender, NetStreamReceivedEventArgs`1 e)
>    en NetSockets.NetBaseStream`1.RaiseOnReceived(T data)
>    en NetSockets.NetObjectStream.ReceivedPayload(Byte[] data)
>    en NetSockets.NetBasePayloadStream`1.ReceivedRaw(Byte[] bytes)
>    en NetSockets.NetBaseStream`1.ThreadedReceive()
>    en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    en System.Threading.ThreadHelper.ThreadStart()

**Comment by MichaelTheShifter** [comment]
ObjectDisposedException...hmmm... maybe something is trying to talk with the OOBE after it has been removed from RAM (disposed of). I'd wait for the OpenGL update to finish - we're working on it.

**Comment by Daniel11420** [comment]
Okay, thanks. It seems like the tutorial isn't really... functional in this version. Thanks anyways. ;)

**Comment by MichaelTheShifter** [comment]
Closing due to a fix already being admistered.
