### ISSUE TITLE
Game crashing at start.

### ISSUE THREAD

**Issue by Daniel11420** [shiftos-game/ShiftOS#114]
Hello again! Another issue. Now, when I launch ShiftOS, this is what happens:

[This compu- ShiftOS.WinForm is not responding..

[This computer is being hijacked]
H|-- ShiftOS.WinForm is not responding..

[Thi-- CRASH
[This compute-- ShiftOS.WinForm is not responding..

That's what happens. It doesn't give me crash reports. Game was running perfectly fine before.

**Comment by MichaelTheShifter** [comment]
Hmmm... I'm not sure if you're on latest AppVeyor or what - I'd stay off them though. My guess is I would go back to one of the early alphas, like Alpha 3 to create your save, then go back to the latest beta. I'm not sure though. That's your only choice unless you want to wait till OpenGL.

**Comment by Daniel11420** [comment]
I just re-opened it a million times and worked
lol
rekt
gg
also crashes right after tutorial
no crash report
