### ISSUE TITLE
OOBE Sometimes Crashes

### ISSUE THREAD

**Issue by wowmom98** [shiftos-game/ShiftOS#2]
Sometimes when you use the `shiftorium.buy{upgrade:"mud_fundamentals"}` the game crashes

**Comment by TheRandomMelon** [comment]
Also, I wanted to add: When OOBE crashes, the only way to kill it is to log out and back in or reboot your PC, which makes this an urgent bug we need to fix.

**Comment by wowmom98** [comment]
Actually its easier than that, do windows key + tab and put the oobe in a desktop 2 and then go into vs and stop it.
But if a user is using it than their hopeless

**Comment by TheRandomMelon** [comment]
what if your Windows key is broken? @wowmom98

**Comment by wowmom98** [comment]
hopeless

**Comment by TheRandomMelon** [comment]
Welp, I'll look into this later.

**Comment by MichaelTheShifter** [comment]
This has been fixed with the newer OOBE
