### ISSUE TITLE
Draggable Windows doesn't work the first time you get it

### ISSUE THREAD

**Issue by wowmom98** [shiftos-game/ShiftOS#3]
Another self explainatory bug

**Comment by ComputeLinux** [comment]
it's because it doesnt re instantate window borders

**Comment by pfgithub** [comment]
can't we just run the window border instantiation on all windows, that doesn't sound hard to do

**Comment by MichaelTheShifter** [comment]
Not sure if this issue is still an issue nowadays. Window dragging should be working fine right after buying the upgrade.
