### ISSUE TITLE
Errors with Mono

### ISSUE THREAD

**Issue by MrDiamond123** [shiftos-game/ShiftOS#33]
Is there a way to use IPv6 over IPv4?
Mono (Which Is the way I'm trying to get ShiftOS Working and Ported) doesn't have MapToIPv4 yet.
> /home/.../ShiftOS-master/ShiftOS.Server/Program.cs(54,54): Error CS1061: Type `System.Net.IPAddress' does not contain a definition for `MapToIPv4' and no extension method `MapToIPv4' of type `System.Net.IPAddress' could be found. Are you missing an assembly reference? (CS1061) (ShiftOS.Server)

**Comment by MrDiamond123** [comment]
Its Also In WebAdmin.cs
> /home/.../ShiftOS-master/ShiftOS.Server/WebAdmin.cs(51,51): Error CS1061: Type `System.Net.IPAddress' does not contain a definition for `MapToIPv4' and no extension method `MapToIPv4' of type `System.Net.IPAddress' could be found. Are you missing an assembly reference? (CS1061) (ShiftOS.Server)

**Comment by ComputeLinux** [comment]
You need to use Mono 4.x, not Mono 3.x.

**Comment by MrDiamond123** [comment]
K

**Comment by MichaelTheShifter** [comment]
I've been having this problem as well on my Ubuntu server which the forum runs on. Try using Mono 4.x like @ComputeLinux said.

**Comment by MrDiamond123** [comment]
http://imgur.com/a/V5Ue9

**Comment by MrDiamond123** [comment]
I have to downgrade It seems like

**Comment by MichaelTheShifter** [comment]
Are you running using the .NET 4.5 profile or .NET 4.0? ShiftOS's components as well as the game itself are all written in .NET 4.5.

**Comment by MrDiamond123** [comment]
I'm running in .NET 4.6

That Part is working now but now I'm getting errors in AudioManager.cs

Why are you using Windows Media Player?

**Comment by MrDiamond123** [comment]
Just Delete SoundManager.cs and it works

**Comment by ComputeLinux** [comment]
Deleting a critical engine file is not a solution.
WMP is used to play sounds. do you have any better ideas?

**Comment by MrDiamond123** [comment]
I heard there was a VLC API

Also there is a weird text delay when typing, you can't save the game as it saves on a Windows File System not using &HOMEDIR&/ShiftOS (Or Something like that IDK C#)

**Comment by MichaelTheShifter** [comment]
ShiftOS should be saving to `Environment.SpecialFolder.MyDocuments`/ShiftOS.mfs.

I still have to do Linux testing, but my Zorin image is broken and I can't use it.

**Comment by ComputeLinux** [comment]
we could use fmod

**Comment by ComputeLinux** [comment]
we are using naudio

**Comment by MrDiamond123** [comment]
good to know thanks ;)
