### ISSUE TITLE
Somehow teach the user how to use win.open

### ISSUE THREAD

**Issue by wowmom98** [shiftos-game/ShiftOS#4]
Wow, another self explanatory thing

**Comment by wowmom98** [comment]
Why is this trivial? if we want people to play the game they have to know how to play/how the game works...

**Comment by ComputeLinux** [comment]
trivial means its easy to do

**Comment by wowmom98** [comment]
thought the trival meant that there was little point in doing it

**Comment by ComputeLinux** [comment]
not in programing world

**Comment by wowmom98** [comment]
made the tag more clear

**Comment by pfgithub** [comment]
I'm pretty sure we're going to switch to having the command run the application instead of having to win.open

For example: `shiftorium.open`

**Comment by MichaelTheShifter** [comment]
The tutorial implemented in 4.3 should have covered it.
