### ISSUE TITLE
Pay codepoints for shiftnet access

### ISSUE THREAD

**Issue by wowmom98** [shiftos-game/ShiftOS#45]
Suggested by AShifter.

There could be a new program where you set a plan (that you could change at any time) to pay a certain amount of codepoints every week to keep internet access. Plans also have different download speeds and slower speeds are cheaper (of course.)

**Comment by ComputeLinux** [comment]
this isnt real life.

**Comment by ComputeLinux** [comment]
intended for b1

**Comment by MichaelTheShifter** [comment]
Added in beta 1.3.
