### ISSUE TITLE
Crashes too much

### ISSUE THREAD

**Issue by shinyzoruashifter** [shiftos-game/ShiftOS#46]
It crashes when I start the game, I have admin privileges enabled

**Comment by wowmom98** [comment]
Can we have more details like game version?

**Comment by shinyzoruashifter** [comment]
I'm using the latest AppVoyer version

**Comment by wowmom98** [comment]
Can we also have the crash.txt log file?

**Comment by shinyzoruashifter** [comment]
Give me a few

**Comment by shinyzoruashifter** [comment]
It doesn't have a crash.txt in the game folder

**Comment by wowmom98** [comment]
It's kinda hidden, try searching for it

**Comment by shinyzoruashifter** [comment]
There are no subfolders

**Comment by MichaelTheShifter** [comment]
There is no crash.txt. The crash handler isn't working. I just want to know - can you go through your DLL files and EXE files and right click each of them and click 'Properties'?

And when you do that, is there an 'Unblock' option? If so, please enable it on all DLLs/EXEs you can, then try running the game again. Please get back to me if it still crashes.

**Comment by shinyzoruashifter** [comment]
There's no Unblock option on any of them

**Comment by MichaelTheShifter** [comment]
Hmmm... do you already have a ShiftOS save, and if so, is it from before Alpha 4.3?

**Comment by shinyzoruashifter** [comment]
I got it yesterday

**Comment by MichaelTheShifter** [comment]
Hm. And what exactly is the error?

**Comment by shinyzoruashifter** [comment]
It just crashes, no errors

**Comment by MichaelTheShifter** [comment]
Hm. I'll see if I can release a build with a WORKING crash handler.

**Comment by shinyzoruashifter** [comment]
Okay

**Comment by MichaelTheShifter** [comment]
Alright, I'm pushing up a new build of the game to AppVeyor with a crash handler enabled. When it crashes, you should see a dialog asking you if you want to restart the game. Click No, then find the crash.txt file in the game directory (you might have to refresh the Explorer window by pressing F5). Can you send the contents of that file?

**Comment by shinyzoruashifter** [comment]
Give me a few to get the latest version

**Comment by MichaelTheShifter** [comment]
Just know, AppVeyor's being very slow lately so it may take a while before the build passes again.

**Comment by MichaelTheShifter** [comment]
Alright, build's passing again!

**Comment by shinyzoruashifter** [comment]
The for still isn't there

**Comment by shinyzoruashifter** [comment]
*File

**Comment by MichaelTheShifter** [comment]
Did you at least see the dialog box?

**Comment by MichaelTheShifter** [comment]
Should look like this: 
![image](https://cloud.githubusercontent.com/assets/18349904/22613972/067eb4a8-ea4b-11e6-9522-e1401b0b940c.png)

**Comment by shinyzoruashifter** [comment]
Nope, just crashed immediately this time, no dialog box

**Comment by MichaelTheShifter** [comment]
Are you on the latest AppVeyor build? The latest one makes changes to the ShiftOS.Engine.dll so if you only brought over the new WinForms exe, that's not enough.

**Comment by shinyzoruashifter** [comment]
I completely reinstalled the game

**Comment by MichaelTheShifter** [comment]
Oh, then perhaps this crash is something out of the realm of what I can help out with. If my crash handler can't give me info then I'm afraid there's nothing I can do for now. I will have a look at the multi-user domain logs to see if your client is trying to authenticate, though.

**Comment by shinyzoruashifter** [comment]
It now crashes after it says "System initiated"

**Comment by shinyzoruashifter** [comment]
Before it crashed when it got to desktop

**Comment by MichaelTheShifter** [comment]
Okay. So it's loading your save up, then crashing? What mods do you have?

**Comment by shinyzoruashifter** [comment]
None

**Comment by MichaelTheShifter** [comment]
And how far did you get in the game? Like, did you even get a chance to get Shiftorium upgrades etc before the crashing happened?

**Comment by shinyzoruashifter** [comment]
I was in the tutorial still

**Comment by AShifter** [comment]
Try going to your ShiftOS folder, and go to "View" on the top context menu. Click on hidden files. 
![image](https://cloud.githubusercontent.com/assets/10788034/22614218/9cdd22fe-ea3c-11e6-8884-6d5928bbf222.png)

**Comment by MichaelTheShifter** [comment]
OK. Let me have a look. I may have to edit your save to get this to work.

**Comment by shinyzoruashifter** [comment]
![2017-02-03_19-15-32](https://cloud.githubusercontent.com/assets/25539415/22614234/360f8702-ea45-11e6-8a8d-63a4294c5d4b.png)

**Comment by AShifter** [comment]
It was worth a shot. Let Michael edit your save file. He's working on it right now.

**Comment by MichaelTheShifter** [comment]
Actually, I need to know what your in-game username is @shinyzoruashifter

**Comment by shinyzoruashifter** [comment]
shiny_zorua_shifter

**Comment by MichaelTheShifter** [comment]
Alrighty, just advanced your position in the game beyond the tutorial and I also set your engine settings up properly. Try now!

**Comment by shinyzoruashifter** [comment]
Okay, that seems to have worked

**Comment by MichaelTheShifter** [comment]
Alright. That's all the info I need.

**Comment by shinyzoruashifter** [comment]
You should make sure it doesn't do this when you quit during the tutorial.

**Comment by MichaelTheShifter** [comment]
Well, this bug seems to be fixed so I'll close it.
