### ISSUE TITLE
Tutorial and audio manager bug

### ISSUE THREAD

**Issue by MichaelTheShifter** [shiftos-game/ShiftOS#47]
This is a report generated from data collected from issue #46.

It seems that the game, while trying to go through the tutorial sequence will experience a post-save-load startup crash uncaught by the crash handler. This crash can be worked around by setting the `StoryPosition` value of the affected save file to anything above the final tutorial stage, and adding a new `audioVolume` variable with value `1.0` to the `Settings` object in the affective save.

**Comment by shinyzoruashifter** [comment]
There should be a way to restart the story if you want (something I really want actually :P)

**Comment by ComputeLinux** [comment]
i'm stuck on stage 7 :(
