### ISSUE TITLE
OOBE text gets cut off on 1366x768 displays.

### ISSUE THREAD

**Issue by MichaelTheShifter** [shiftos-game/ShiftOS#50]
![Screenshot](https://images.discordapp.net/.eJwVzNENhCAMANBdGIBqCwJuQ5AgF7EE6pe53S_3BnivesaldnWK9LkDHHUmHoeewiOWrAtzuXLsderEDaJITGfLt0xAgx7J4uaJCM1CCOicdUsIYTPern41Bmr7N59e1PcHvwYh0Q.NKp0AvQVOYlHPW56kjrGkvp9R8o?width=1215&height=911)

This bug was found by a Discord user who tried ShiftOS on their laptop at 1366x768 resolution. This screenshot shows the bug in action.

**Comment by MichaelTheShifter** [comment]
May I have a situation update on this?

**Comment by aren-cllc** [comment]
I have a laptop with this resolution. It still happens, what we could do is split the long sentences in half.

**Comment by MichaelTheShifter** [comment]
That should work perfectly, actually. Still don't know why the label isn't wrapping text.
