### ISSUE TITLE
Way to download c# mods and dynamically load them

### ISSUE THREAD

**Issue by ComputeLinux** [shiftos-game/ShiftOS#57]
Would be away to make c# modding more seamless

**Comment by MichaelTheShifter** [comment]
Actually, This wouldn't be too difficult. All we'd have to do is somehow when the .stp file subsystem is added to the engine, have a way to distinguish between C# mods, lua apps and system apps (possibly a header inside the file telling us what type of file it is maybe?) and if it's a C# mod, take the contents of the file and extract them to Environment.CurrentDirectory, then invoke an app launcher populate to reset the AL and the engine will do the rest.

**Comment by MichaelTheShifter** [comment]
While it has sort of a hackmud-style user generation system, it works well. I can see this being a major mechanic once I do the client-side.

**Comment by mihail-mojsoski** [comment]
It isn't difficult, just use Activator and a Reflective Enumerator.

For the reflective enumerator you can use this code:
``` c#
public static IEnumerable<Type> GetEnumerableOfType<T>(string dll) where T : class
{
    return Assembly
         .LoadFrom(dll)
         .GetTypes()
         .Where(myType => myType.IsClass && !myType.IsAbstract && myType.IsSubclassOf(typeof(T)))
         .ToList();
}
```

And you can use that method to add all the classes you need from an abstract class into a list, e.g. this is in an other DLL:
```c#
public class Something : MyAbstractClass
{
    public override void DoSomething()
    {
        Console.WriteLine("Hello World\n");
    }
}
```

And you can load all the classes that inherit `MyAbstractClass` from a DLL into a list like this:
```c#
List<MyAbstractClass> mylist = new List<MyAbstractClass>();
List<Type> dlltypes = new List<Type>();
dlltypes.AddRange(GetEnumerableOfType<MyAbstractClass>("mod.dll"));
foreach(Type type in dlltypes)
    mylist.Add((MyAbstractClass)Activator.CreateInstance(type));
```

And after that you can access the `DoSomething` method like this in every loaded dll like this:
```c#
foreach(MyAbstractClass mymod in mylist)
{
    mymod.DoSomething();
}
```

**Comment by MichaelTheShifter** [comment]
Our engine already supports modding. All we need to do is make the app
installer bring dlls to the exec dir. ShiftOS's engine can do hot-swapping,
dynamic loading etc.
