### ISSUE TITLE
Custom app launcher

### ISSUE THREAD

**Issue by aren-cllc** [shiftos-game/ShiftOS#59]
sort-of-but-not-really requested by discord user lolerr

**Comment by dcriste** [comment]
requested by me

**Comment by MichaelTheShifter** [comment]
ya beat me to it...

**Comment by aren-cllc** [comment]
:P

**Comment by dcriste** [comment]
:P

**Comment by aren-cllc** [comment]
Closing this issue, Michael made #60 which describes everything much better
