### ISSUE TITLE
Advanced App Launcher

### ISSUE THREAD

**Issue by MichaelTheShifter** [shiftos-game/ShiftOS#60]
- Add a KDE-like advanced app launcher, possibly downloadable through Shiftnet.
 - Make an application that allows users to switch between app launchers.
 - Add modding/scripting capabilities for creating custom advanced app launchers.

**Comment by ComputeLinux** [comment]
Add a KDE-like advanced app launcher, possibly downloadable through Shiftnet. yesyesyseyseysyeyseyseyseyseyawuefahsfnpaiogsdifhb m;/mbuilkdi, lfjmndfmk,

**Comment by MichaelTheShifter** [comment]
....problem exists between keyboard and cap?

**Comment by MichaelTheShifter** [comment]
Advanced AL is in.
