### ISSUE TITLE
Better terminal emulator

### ISSUE THREAD

**Issue by aren-cllc** [shiftos-game/ShiftOS#61]
Suggested by multiple people in the discord having issues with the current terminal

**Comment by ComputeLinux** [comment]
what's wring with the current one
it's a flipping box you type words into
then it puts more words

**Comment by ComputeLinux** [comment]
i cllc'd the wrong button

**Comment by aren-cllc** [comment]
You can remove previous text, and mess up everything. :/

**Comment by ComputeLinux** [comment]
oh shit that's my problem then

**Comment by MichaelTheShifter** [comment]
THIS is the right issue. FIXED.
