### ISSUE TITLE
More ways to earn codepoints

### ISSUE THREAD

**Issue by aren-cllc** [shiftos-game/ShiftOS#62]
Pong is not enough to buy expensive upgrades.

**Comment by MichaelTheShifter** [comment]
We are aware that there are not many ways to earn Codepoints, however in beta 1 there are shops, which allow you to set arbitrary prices on items - and when you pay for an item, those codepoints go to the shop owner.

As for other ways, maybe we could add another game to ShiftOS? Possibly something like Knowledge Input but with more than just saying as many words related to a topic as possible?

**Comment by aren-cllc** [comment]
Another game would be nice, however, I have no idea what a good game would be.

**Comment by vicr123** [comment]
Maybe Minesweeper? Shiftsweeper? It can't be *too* hard to code 😄 
If you hit a mine you forfeit all codepoints you earned, and if you win, you get codepoints depending on your speed

**Comment by aren-cllc** [comment]
Hangman could be implemented, I could have a database of words, the codepoints you get would depend on the amount of times you guessed, I have no idea how to implement "Shiftsweeper" though. Maybe someone else could look into that.

**Comment by aren-cllc** [comment]
A wild ShiftLetters appeared!
