### ISSUE TITLE
Creation of legion seems to break the legion tab

### ISSUE THREAD

**Issue by ComputeLinux** [shiftos-game/ShiftOS#66]
I tried to create a PublicInviteOnly legion and now I can't use the legions function, Create legion half works but nothing else will even select

**Comment by ComputeLinux** [comment]
It works now, what the fuck?

**Comment by MichaelTheShifter** [comment]
Possibly MUD slowing down, maybe? Sometimes it likes to drop connections for some reason. Remember to check `mud.status` if you feel something isn't working right. If `IsConnected` is false, then run `mud.connect{addr:"michaeltheshifter.me", port:"13370"}` to reconnect.

**Comment by aren-cllc** [comment]
I think this issue can be closed as it was probably a disconnect.
