### ISSUE TITLE
Tutorial breaking

### ISSUE THREAD

**Issue by LMGN** [shiftos-game/ShiftOS#78]
After you enter your username and password, you're greeted with this
http://sx.thelmgn.com/2017/02/ShiftOS.WinForms_2017-02-23_22-37-44.png

And it launches the setup window again.

**Comment by LMGN** [comment]
After it gets throught the tutorial
http://sx.thelmgn.com/2017/02/ShiftOS.WinForms_2017-02-23_22-39-59.png

**Comment by craftxbox** [comment]
Are you using the latest appveyor build?

**Comment by aren-cllc** [comment]
Beta 1.1 /is/ the latest appveyor build

**Comment by craftxbox** [comment]
they havent specified what they actually are using, so hence im asking

**Comment by aren-cllc** [comment]
I assume this is on Windows?

**Comment by MichaelTheShifter** [comment]
...Yes it is...

**Comment by craftxbox** [comment]
@MichaelTheShifter, WINE exists

**Comment by aren-cllc** [comment]
Yeah, I just wanted to make sure, that's why I also asked in Discord and edited my comment ;)

**Comment by MichaelTheShifter** [comment]
Hmmmm this doesn't seem like Windows to me. Looks like a Linux distro with a Windows-like theme applied and the game's running in wine. Linux/Mono/Wine support isn't in yet.

**Comment by aren-cllc** [comment]
Yeah, that's why I asked him in Discord :P

**Comment by MichaelTheShifter** [comment]
Assuming unsupported platform... closing issue.

**Comment by LMGN** [comment]
@MichaelTheShifter it's Windows 8.1 with .NET 4.6

**Comment by ComputeLinux** [comment]
@LMGN i've fixed it
