### ISSUE TITLE
Add better MUD client auth system

### ISSUE THREAD

**Issue by wowmom98** [shiftos-game/ShiftOS#8]
"Though early testing, it’s clear the transition to ASP.NET will work. While Nancy would crash with a pitifully low number of requests, ASP.NET does not drop any requests at all with several thousand. " - FreeSO

**Comment by MichaelTheShifter** [comment]
ASP.NET shouldn't be too hard for the admin panel - considering it has everything we need. The problem with ASP.NET is I am not sure we can embed it inside the MUD console process and have ASP.NET automatically connect to the MUD on start. It's worth looking into, though.

**Comment by ComputeLinux** [comment]
I'm not suggesting we use ASP.net, just that we need to stop using Nancy. It crashed under ~10 non-simultaneous queries. That's bad.

**Comment by MichaelTheShifter** [comment]
Well seeings as you need to provide a username & password to the MUD to get your save, I can say that's a worthy client auth system...
