### ISSUE TITLE
Pong.Designer.cs: Cannot process ShiftoriumFrontend.UpgradeInstalled("pong_increased_paddle_size")

### ISSUE THREAD

**Issue by AShifter** [shiftos-game/ShiftOS#83]
It seems that there are issues with the code for the increased pong paddle size upgrade.
![capture](https://cloud.githubusercontent.com/assets/10788034/23318491/ea6138e0-fa8f-11e6-8aae-d747f77a9a16.PNG)
![code](https://cloud.githubusercontent.com/assets/10788034/23318492/ec785c1c-fa8f-11e6-8650-1d78f0b1aa10.PNG)

**Comment by MichaelTheShifter** [comment]
ARGH. This is EXACTLY WHY I keep saying DON'T USE THE SHIFTORIUM OR OTHER ENGINE UTILITIES IN THE GOD DAMN DESIGNER.

# EVER.

**Comment by AShifter** [comment]
I... Didn't do anything... To the code... :(

**Comment by craftxbox** [comment]
i fixed it in my latest pull request.

**Comment by mihail-mojsoski** [comment]
Just put it in the Load event ffs

**Comment by MichaelTheShifter** [comment]
@mihail-mojsoski 

# **THANK YOU.**
